# Generated by Django 5.1.4 on 2024-12-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attendance_attendee_alter_attendance_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.attendee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(default=1988, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ticket',
            field=models.ForeignKey(default=1988, on_delete=django.db.models.deletion.CASCADE, to='core.ticket'),
            preserve_default=False,
        ),
    ]
