# Generated by Django 5.1.4 on 2024-12-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendance_attendee_alter_attendance_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_type',
            new_name='role',
        ),
    ]
