# Generated by Django 5.1.4 on 2024-12-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_type_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='max_nb_ticket',
            new_name='quantity',
        ),
    ]
